[LangOptions]
LanguageName=简体中文
LanguageID=$0804
LanguageCodePage=936

[Messages]
SetupAppTitle=安装
SetupWindowTitle=安装 - %1
UninstallAppTitle=卸载
UninstallAppFullTitle=%1 卸载
InformationTitle=信息
ConfirmTitle=确认
ErrorTitle=错误
SetupLdrStartupMessage=现在将安装 %1。是否继续？
SetupAppRunningError=安装程序发现 %1 正在运行。%n%n请先关闭程序，然后点击“确定”继续。
UninstallAppRunningError=卸载程序发现 %1 正在运行。%n%n请先关闭程序，然后点击“确定”继续。
ExitSetupTitle=退出安装程序
ExitSetupMessage=安装尚未完成。如果现在退出，将不会安装该程序。%n%n确定退出吗？
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安装(&I)
ButtonOK=确定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonNo=否(&N)
ButtonFinish=完成(&F)
ButtonBrowse=浏览(&B)...
ButtonWizardBrowse=浏览(&R)...
ClickNext=点击“下一步”继续，或点击“取消”退出安装程序。
BrowseDialogTitle=选择安装文件夹
BrowseDialogLabel=请在下面的列表中选择文件夹，然后点击“确定”。
NewFolderName=新建文件夹
WelcomeLabel1=欢迎使用 [name] 安装向导
WelcomeLabel2=现在将安装 [name/ver] 到您的电脑中。%n%n建议您在继续前关闭其他应用程序。
WizardSelectDir=选择安装位置
SelectDirDesc=您想将 [name] 安装在哪里？
SelectDirLabel3=安装程序将把 [name] 安装到以下文件夹。
SelectDirBrowseLabel=点击“下一步”继续。如需选择其他文件夹，请点击“浏览”。
DiskSpaceGBLabel=至少需要 [gb] GB 可用磁盘空间。
DiskSpaceMBLabel=至少需要 [mb] MB 可用磁盘空间。
CannotInstallToNetworkDrive=安装程序无法安装到网络驱动器。
CannotInstallToUNCPath=安装程序无法安装到 UNC 路径。
WizardSelectTasks=选择附加任务
SelectTasksDesc=选择要创建的快捷方式。
SelectTasksLabel2=桌面快捷方式默认选中，也可以取消，然后点击“下一步”。
WizardReady=准备安装
ReadyLabel1=安装程序已准备好安装 [name]。
ReadyLabel2a=点击“安装”继续；如需修改设置，请点击“上一步”。
ReadyLabel2b=点击“安装”继续。
ReadyMemoDir=安装位置：
ReadyMemoGroup=开始菜单文件夹：
ReadyMemoTasks=快捷方式：
WizardPreparing=准备安装
PreparingDesc=安装程序正在准备安装 [name]。
ApplicationsFound=以下应用程序正在使用需要更新的文件。建议允许安装程序自动关闭这些应用程序。
CloseApplications=自动关闭应用程序(&A)
DontCloseApplications=不要关闭应用程序(&D)
WizardInstalling=正在安装
InstallingLabel=正在安装 [name]，请稍候。
FinishedHeadingLabel=[name] 安装完成
FinishedLabelNoIcons=[name] 已成功安装。
FinishedLabel=[name] 已成功安装。您可以通过快捷方式运行程序。
ClickFinish=点击“完成”退出安装程序。
RunEntryExec=运行 %1
StatusClosingApplications=正在关闭应用程序...
StatusCreateDirs=正在创建目录...
StatusExtractFiles=正在提取文件...
StatusCreateIcons=正在创建快捷方式...
StatusCreateRegistryEntries=正在创建注册表项...
StatusSavingUninstall=正在保存卸载信息...
StatusRunProgram=正在完成安装...
StatusRollback=正在撤销更改...
ConfirmUninstall=确定要完全移除 %1 及其所有组件吗？
UninstallStatusLabel=正在从您的电脑中移除 %1，请稍候。
UninstalledAll=%1 已成功移除。
WizardUninstalling=卸载状态
StatusUninstalling=正在卸载 %1...

[CustomMessages]
AdditionalIcons=附加快捷方式：
CreateDesktopIcon=创建桌面快捷方式
ButtonCancel=取消
LaunchProgram=运行 %1
UninstallProgram=卸载 %1
UninstallDataTitle=卸载用户数据
UninstallDataPrompt=请选择用户数据处理方式：
KeepUserDataOption=保留用户数据
DeleteUserDataOption=完全删除用户数据
UninstallContinueButton=继续卸载
